# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-26 15:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserAccount', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='course',
            field=models.CharField(max_length=10),
        ),
    ]
