# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-14 06:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserAccount', '0004_auto_20170707_0630'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='b_type',
            field=models.CharField(choices=[('S', 'S'), ('D', 'D')], default='S', max_length=1),
        ),
        migrations.AddField(
            model_name='book',
            name='price',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
