# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-30 06:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserAccount', '0004_book_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='pub_year',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='book',
            name='user_book_id',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='UserAccount.Profile'),
        ),
    ]
