# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-14 07:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserAccount', '0005_auto_20170714_0643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='user_book_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserAccount.Profile'),
        ),
    ]
