# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-30 07:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserAccount', '0006_auto_20170630_0646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(upload_to='BookImages'),
        ),
    ]
