# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-30 07:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserAccount', '0007_auto_20170630_0743'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='image',
        ),
        migrations.AddField(
            model_name='book',
            name='book_pic',
            field=models.ImageField(default='BookImages/default_pic.png', upload_to='BookImages'),
        ),
    ]
