# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-14 07:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserAccount', '0007_auto_20170714_0736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='user_book_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
