# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-14 07:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserAccount', '0008_auto_20170714_0749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='user_book_id',
            field=models.IntegerField(),
        ),
    ]
