# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-16 06:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserAccount', '0010_book_book_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_pic',
            field=models.ImageField(blank=True, upload_to='BookImages'),
        ),
    ]
