# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-21 16:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserAccount', '0013_auto_20170721_2218'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='user_book_id',
            new_name='user_book',
        ),
    ]
