# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-22 07:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserAccount', '0014_auto_20170721_2219'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='created_time',
            field=models.DateField(default=datetime.datetime(2017, 7, 22, 7, 50, 22, 109305)),
        ),
    ]
