# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-23 11:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserAccount', '0015_book_created_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
