# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 14:27
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('UserAccount', '0017_auto_20170724_0902'),
    ]

    operations = [
        migrations.CreateModel(
            name='Counselling',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name1', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('college', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=10)),
                ('branch', models.CharField(max_length=50)),
                ('c_choices', models.CharField(choices=[('PL', 'Placement'), ('CA', 'Career'), ('ED', 'Education'), ('PS', 'Psychology')], default='CA', max_length=2)),
                ('description', models.CharField(max_length=1000)),
                ('status_c', models.CharField(choices=[('UR', 'Urgent'), ('WA', 'Wait')], default='WA', max_length=2)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='book',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 25, 19, 57, 25, 792000)),
        ),
    ]
