# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 14:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserAccount', '0018_auto_20170725_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
