# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-26 16:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserAccount', '0019_auto_20170725_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='b_type',
            field=models.CharField(choices=[('Sell', 'Sell'), ('Donate', 'Donate')], default='Sell', max_length=1),
        ),
        migrations.AlterField(
            model_name='book',
            name='negotiable',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=3),
        ),
    ]
