# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-27 09:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserAccount', '0020_auto_20170726_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='negotiable',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=10),
        ),
    ]
