# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-27 09:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserAccount', '0021_auto_20170727_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='b_type',
            field=models.CharField(choices=[('Sell', 'Sell'), ('Donate', 'Donate')], default='Sell', max_length=10),
        ),
    ]
