# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-28 10:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserAccount', '0022_auto_20170727_1442'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='counselling',
            name='user',
        ),
    ]
